import {matchParticlePositions,smootherStep} from './morph-matching';
type State={current:{dark:boolean,reduced:boolean}};
type Pixel={x:number,y:number,l:number,r:number,g:number,b:number,wing:number,seed:number};
const clamp=(v:number)=>Math.max(0,Math.min(1,v));const ease=(v:number)=>{const t=clamp(v);return t*t*(3-2*t)};
function img(url:string){return new Promise<HTMLImageElement>((r,j)=>{const i=new Image();i.onload=()=>r(i);i.onerror=j;i.src=url})}
function masked(image:HTMLImageElement,branch=false){const c=document.createElement('canvas');c.width=image.width;c.height=image.height;const ctx=c.getContext('2d')!;ctx.drawImage(image,0,0);const d=ctx.getImageData(0,0,c.width,c.height);for(let i=0;i<d.data.length;i+=4){const r=d.data[i],g=d.data[i+1],b=d.data[i+2],lum=.299*r+.587*g+.114*b,chroma=Math.max(r,g,b)-Math.min(r,g,b);let a=Math.max(clamp((chroma-5)/17),1-clamp((lum-44)/48));if(branch)a=Math.max(a,clamp((lum-216)/24));d.data[i+3]=Math.round(a*255)}ctx.putImageData(d,0,0);return c}
function samples(c:HTMLCanvasElement,bee=false){const s=400;const tmp=document.createElement('canvas');tmp.width=tmp.height=s;const ctx=tmp.getContext('2d')!;ctx.drawImage(c,0,0,s,s);const d=ctx.getImageData(0,0,s,s).data;const list:Pixel[]=[];let seed=9831;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};for(let y=0;y<s;y++)for(let x=0;x<s;x++){const i=(y*s+x)*4;if(d[i+3]<180)continue;list.push({x:x/s-.5,y:y/s-.5,l:(d[i]*.299+d[i+1]*.587+d[i+2]*.114)/255,r:d[i],g:d[i+1],b:d[i+2],wing:bee&&y<s*.53&&(x<s*.36||x>s*.72)?1:0,seed:rand()})}for(let i=list.length-1;i>0;i--){const j=Math.floor(rand()*(i+1));[list[i],list[j]]=[list[j],list[i]]}return list}
export function canvasFallback(host:HTMLDivElement,state:State){let stopped=false,raf=0,time=0,last=0,scroll=window.scrollY,w=window.innerWidth,h=window.innerHeight;const canvas=document.createElement('canvas');const ctx=canvas.getContext('2d',{alpha:true})!;host.appendChild(canvas);const mobile=()=>w<641;let head:HTMLCanvasElement,bee:HTMLCanvasElement,branch:HTMLCanvasElement;let hs:Pixel[]=[],bs:Pixel[]=[];let loaded=false;
const get=(id:string)=>{const el=document.getElementById(id);const b=el?.getBoundingClientRect();return{top:(b?.top??0)+window.scrollY,height:b?.height??0}};let bounds={hero:h*3,services:get('services'),about:get('about'),contact:get('contact')};const measure=()=>{bounds={hero:document.querySelector('.hero-runway')?.getBoundingClientRect().height??h*3,services:get('services'),about:get('about'),contact:get('contact')};start()};
Promise.all([img('/chris-conley-bust.webp'),img('/honeybee-reference.webp'),img('/footer-branch.webp')]).then(async([a,b,c])=>{if(stopped)return;head=masked(a);bee=masked(b);branch=masked(c,true);const count=mobile()?16000:32000;const headSamples=samples(head),beeSamples=samples(bee,true);hs=Array.from({length:count},(_,i)=>headSamples[i%headSamples.length]);const raw=Array.from({length:count},(_,i)=>beeSamples[i%beeSamples.length]);const from=new Float32Array(count*2),to=new Float32Array(count*2);for(let i=0;i<count;i++){from.set([hs[i].x,hs[i].y],i*2);to.set([raw[i].x,raw[i].y],i*2)}const order=matchParticlePositions(from,to,2);bs=Array.from(order,i=>raw[i]);loaded=true;host.dataset.ready='true';host.dataset.renderer='canvas';measure()});
function draw(now:number){raf=0;if(stopped)return;if(now-last<30&&Math.abs(window.scrollY-scroll)<.5){raf=requestAnimationFrame(draw);return}const dt=Math.min(.05,(now-last)/1000||.016);last=now;const {dark,reduced}=state.current;if(!reduced)time+=dt;const target=window.scrollY;scroll=reduced?target:scroll+(target-scroll)*(1-Math.exp(-12*dt));ctx.clearRect(0,0,w,h);if(!loaded)return;let x=mobile()?.50:.555,y=mobile()?.39:.405,size=h*(mobile()?.42:.625),m=0,opacity=1,rot=0,visible=true,showBranch=false;const p=scroll/h;
if(reduced){visible=scroll<h*.75;if(scroll+h>bounds.contact.top){m=1;showBranch=true;visible=true;x=mobile()?.55:.81;y=(bounds.contact.top-scroll)/h+(mobile()?.80:.32)*Math.min(bounds.contact.height/h,1.5);size=h*.21}}
else if(scroll<bounds.hero-h){m=smootherStep((p-.20)/1.35);if(p>1.72){const t=ease((p-1.72)/Math.max(.35,(bounds.hero/h-1)-1.72));x=x+(1.18-x)*t;y=y+(.78-y)*t+Math.sin(t*Math.PI)*.15;size*=1-.75*t;rot=-Math.sin(t*Math.PI)*.32;opacity=1-ease((t-.86)/.14)}}
else if(scroll+h>bounds.services.top&&scroll<bounds.about.top-h*.35){m=1;const t=clamp((scroll+h-bounds.services.top)/(bounds.services.height+h*.65));x=-.15+1.27*t;y=.2+Math.sin(t*Math.PI*1.7)*.045;size=h*.16;opacity=Math.min(1,t*8,(1-t)*8)}
else if(scroll+h>bounds.contact.top){m=1;const t=ease((scroll+h-bounds.contact.top)/(h*.8));x=1.15+((mobile()?.55:.81)-1.15)*t;y=(bounds.contact.top-scroll)/h+(mobile()?.80:.32)*Math.min(bounds.contact.height/h,1.5)+Math.sin(time*2.2)*.007;size=h*.21;showBranch=true;rot=-.08}else visible=false;
if(showBranch){const by=(bounds.contact.top-scroll)+(mobile()?.86:.51)*Math.min(bounds.contact.height/h,1.5)*h;const bw=h*(mobile()?.54:.68);ctx.drawImage(branch,(mobile()?.70:.87)*w-bw/2,by-bw*(branch.height/branch.width)/2,bw,bw*(branch.height/branch.width))}
if(visible){
ctx.save();ctx.translate(x*w,y*h);ctx.rotate(rot);
const departure=ease(m/.12),arrival=ease((m-.87)/.13);
if(!dark){ctx.globalAlpha=opacity*(1-departure);if(departure<1)ctx.drawImage(head,-size/2,-size/2,size,size);ctx.globalAlpha=opacity*arrival;if(arrival>0)ctx.drawImage(bee,-size/2,-size/2,size,size)}
const particleAlpha=dark?1:Math.min(1,departure*1.35)*(1-arrival);
ctx.globalAlpha=Math.max(0,opacity)*particleAlpha;
if(particleAlpha>.001){
const count=hs.length,arc=Math.sin(m*Math.PI),wingEase=ease((m-.65)/.35);
const paths=new Map<number,Path2D>();
for(let i=0;i<count;i++){const a=hs[i],b=bs[i],lum=a.l*(1-m)+b.l*m;
let key:number;if(dark){key=Math.min(7,Math.floor(lum*8))}else{const rr=Math.min(7,Math.round((a.r*(1-m)+b.r*m)/36.43)),gg=Math.min(7,Math.round((a.g*(1-m)+b.g*m)/36.43)),bb=Math.min(7,Math.round((a.b*(1-m)+b.b*m)/36.43));key=(rr<<6)|(gg<<3)|bb}
let path=paths.get(key);if(!path){path=new Path2D();paths.set(key,path)}
const px=(a.x*(1-m)+b.x*m+Math.sin(a.seed*6.283)*arc*.012)*size;
const py=(a.y*(1-m)+b.y*m+Math.cos(a.seed*6.283)*arc*.010+(!reduced?Math.sin(time*29)*b.wing*.009*m*wingEase:0))*size;
const r=(mobile()?.82:1.0)*(dark?1:1.3)*(1+a.seed*.25);path.rect(px,py,r,r)}
paths.forEach((path,key)=>{ctx.fillStyle=dark?`rgba(143,192,240,${.22+key*.095})`:`rgb(${Math.round((key>>6)*36.43)},${Math.round(((key>>3)&7)*36.43)},${Math.round((key&7)*36.43)})`;ctx.fill(path)})}
ctx.restore()}
if(!reduced&&(visible&&m>.9||showBranch)||Math.abs(target-scroll)>.3)raf=requestAnimationFrame(draw)}
function start(){if(!raf&&!stopped){last=performance.now();raf=requestAnimationFrame(draw)}}const resize=()=>{w=window.innerWidth;h=window.innerHeight;const dpr=Math.min(window.devicePixelRatio,1.5);canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);measure()};const onVisibility=()=>{if(document.hidden){cancelAnimationFrame(raf);raf=0}else start()};const ro=new ResizeObserver(measure);ro.observe(document.body);window.addEventListener('scroll',start,{passive:true});window.addEventListener('resize',resize);window.addEventListener('fundi-scene-change',measure);window.addEventListener('fundi-appearance',measure);document.addEventListener('visibilitychange',onVisibility);resize();return()=>{stopped=true;cancelAnimationFrame(raf);ro.disconnect();canvas.remove();window.removeEventListener('scroll',start);window.removeEventListener('resize',resize);window.removeEventListener('fundi-scene-change',measure);window.removeEventListener('fundi-appearance',measure);document.removeEventListener('visibilitychange',onVisibility)}}
