"use client";
import {useEffect,useState} from 'react';
import HeroPortrait from './hero-portrait';
import WorkGallery from './work-gallery';
import SculptureReveal from './sculpture-reveal';
import DeviceShowcase from './device-showcase';
import DiscoveryTestimonial from './discovery-testimonial';
import {ArrowUpRight,ArrowDown,Sun,Moon,Menu,X,Accessibility,Layers,Users,BookOpen} from 'lucide-react';
import {Dialog,DialogTrigger,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Switch} from '@/components/ui/switch';
const booking='https://cal.com/theaifundi/intro';
const projects=[
{name:'Kiddo',type:'AI application',image:'kiddo',description:'Childcare documentation, from voice to portfolio.',url:'https://kiddo.now/'},
{name:'Discovery Child Care',type:'Childcare website',image:'discovery-childcare',description:'A clear, welcoming introduction for families exploring care.',url:'https://discoverychildcare.co/'},
{name:'Greenjack Capital',type:'Financial services website',image:'greenjack-capital',description:'Private capital advisory, with a clear path from interest to inquiry.',url:'https://greenjackcapital.com/'},
{name:'MacArthur Flournoy',type:'Personal brand website',image:'macarthur-flournoy',description:'Leadership, speaking and writing in one considered digital home.',url:'https://macarthurflournoy.com/'},
{name:'Dolce Flowers',type:'Floral brand website',image:'dolce-flowers',description:'Flowers for milestones, celebrations and moments worth remembering.',url:'https://dolceflowersxo.com/'},
{name:'Jimi Nu',type:'Artist website',image:'jimi-nu',description:'A cinematic home for music, films, tour dates and booking.',url:'https://www.realjiminu.com/'},
{name:'Across the King’s River',type:'Community & membership',image:'kings-river',description:'A home for African wisdom and spiritual connection.',url:'https://acrossthekingsriver.com/'},
{name:'Blooms & Botanicals',type:'Brand website',image:'blooms-botanicals',description:'Floral design and plant styling, brought online.',url:'https://bloomsbotanicals.com/'},
{name:'Hakuna Matata',type:'Daycare website',image:'hakuna-matata',description:'A welcoming, bilingual home for a local daycare.',url:'https://hakunamatata.biz/'},
{name:'Delta Personal Services',type:'Recruitment website',image:'delta-personal',description:'Connecting international nurses with opportunity.',url:'https://deltapersonalservice.biz/'},
{name:'Precision Fabricated Components',type:'Manufacturing website',image:'precision-fabricated',description:'A clear digital presence for a metal fabrication business.',url:'https://www.precisionfabricated.com/'},
{name:'St. Annis Baptist Church',type:'Community website',image:'st-annis',description:'Faith, community, and worship services.',url:'https://stannispbc.net/'},
{name:'Prisms & Platters',type:'Food & travel website',image:'prisms-platters',description:'Food and travel discoveries from the Bay Area.',url:'https://prismsandplatters.com/'}];
const services=[['Websites','A site that explains your business clearly and makes the next step easy for your customers.','Business websites · Landing pages · Redesigns'],['Applications','Useful tools built around the way your team works, from internal dashboards to customer-facing apps.','Web apps · Internal tools · Customer portals'],['AI systems','Put repetitive work on a better footing. I build practical workflows and help your team learn to run them.','Automations · Content workflows · Integrations'],['AI opportunity audits','We walk through your business, find where AI can help, and agree on a sensible place to start.','Business review · Priorities · Action plan']];
import {faqs} from './site-content';
type Pref={theme:string,size:number,reduce:boolean,contrast:boolean,mono:boolean,underlines:boolean,readable:boolean};
const defaults:Pref={theme:'device',size:100,reduce:false,contrast:false,mono:false,underlines:false,readable:false};
function CTA({children='Let’s build your idea',primary=false}:{children?:React.ReactNode,primary?:boolean}){return <a className={'button '+(primary?'button-primary':'')} href={booking} target="_blank" rel="noopener noreferrer">{children}<ArrowUpRight aria-hidden="true"/></a>}
export default function Home(){const [pref,setPref]=useState<Pref>(defaults);const [loaded,setLoaded]=useState(false);const [dark,setDark]=useState(true);const [menu,setMenu]=useState(false);const [email,setEmail]=useState('');const [audit,setAudit]=useState('');
useEffect(()=>{let saved={};try{saved=JSON.parse(localStorage.getItem('fundi-appearance')||'{}')}catch{}setPref({...defaults,reduce:matchMedia('(prefers-reduced-motion:reduce)').matches,...saved});setLoaded(true)},[]);
useEffect(()=>{if(!loaded)return;const mq=matchMedia('(prefers-color-scheme:dark)');const apply=()=>{const isDark=pref.theme==='device'?mq.matches:pref.theme==='dark';setDark(isDark);document.documentElement.dataset.theme=isDark?'dark':'light';};apply();mq.addEventListener('change',apply);const d=document.documentElement;d.dataset.motion=pref.reduce?'reduce':'full';for(const k of ['contrast','mono','underlines','readable'] as const)d.dataset[k]=String(pref[k]);d.style.fontSize=pref.size+'%';try{localStorage.setItem('fundi-appearance',JSON.stringify(pref))}catch{}window.dispatchEvent(new Event('fundi-appearance'));return()=>mq.removeEventListener('change',apply)},[pref,loaded]);
useEffect(()=>{
  if(!loaded||pref.reduce)return;
  let cancelled=false,cleanup=()=>{};
  Promise.all([import('gsap'),import('gsap/ScrollTrigger'),import('lenis')]).then(([{gsap},{ScrollTrigger},{default:Lenis}])=>{
    if(cancelled)return;
    gsap.registerPlugin(ScrollTrigger);
    const lenis=new Lenis({duration:1.0,smoothWheel:true,anchors:true});
    lenis.on('scroll',ScrollTrigger.update);
    const layoutChanged=()=>{
      lenis.resize();
      // Keep the existing smooth-scroll controller aligned with the position
      // preserved when the 3D runway expands or falls back to the static hero.
      lenis.scrollTo(window.scrollY,{immediate:true,force:true});
    };
    window.addEventListener('fundi-layout-change',layoutChanged);
    const raf=(t:number)=>lenis.raf(t*1000);
    gsap.ticker.add(raf);
    cleanup=()=>{window.removeEventListener('fundi-layout-change',layoutChanged);gsap.ticker.remove(raf);lenis.destroy()};
  }).catch(()=>{});
  return()=>{cancelled=true;cleanup()};
},[loaded,pref.reduce]);
async function subscribe(e:React.FormEvent){e.preventDefault();setAudit('sending');try{const body=new FormData();body.append('email_address',email);const response=await fetch('https://app.kit.com/forms/9726759/subscriptions',{method:'POST',headers:{Accept:'application/json'},body});const data=await response.json() as {status?:string};setAudit(response.ok&&data.status==='success'?'success':'error')}catch{setAudit('error')}}
const update=(k:keyof Pref,v:Pref[keyof Pref])=>setPref(p=>({...p,[k]:v}));
return <><a href="#work" className="skip">Skip to work</a><header className="nav hero-fade"><div className="shell nav-inner"><a className="wordmark" href="#top" aria-label="The AI Fundi home">the ai fundi<span>+</span></a><nav aria-label="Main navigation" className="nav-links"><a href="#work">Work</a><a href="#services">Services</a><a href="#about">The Fundi</a><a href="#lab">The Lab</a></nav><div className="nav-right"><button className="icon-button" onClick={()=>update('theme',dark?'light':'dark')} aria-label={dark?'Switch to light mode':'Switch to dark mode'}>{dark?<Sun/>:<Moon/>}</button><CTA>Let’s talk</CTA><button className="icon-button mobile-menu" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div>{menu&&<nav className="mobile-nav" aria-label="Mobile navigation">{[['Work','work'],['Services','services'],['The Fundi','about'],['The Lab','lab'],['Let’s talk','contact']].map(([label,id])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{label}</a>)}</nav>}</div></header>
<main id="top"><section className="hero-runway" aria-label="Welcome"><div className="hero-sticky"><HeroPortrait/><div className="hero-intro hero-fade"><div className="eyebrow">Independent builder. Practical AI.</div><p>Based in Germany.<br/>Building for businesses everywhere.</p></div><div className="hero-caption hero-fade"><strong>Chris Conley</strong><br/>The AI Fundi</div><div className="hero-bottom hero-fade"><h1>Websites. Apps.<br/>Built to <span>work.</span></h1><div className="hero-cta"><p>You bring the idea.<br/>I help you make it happen.</p><CTA primary>Build your idea</CTA></div></div><a className="scroll-cue hero-fade" href="#work"><ArrowDown/> SCROLL TO EXPLORE</a><span className="hero-index hero-fade">DESIGN / BUILD / LAUNCH</span></div></section>
<WorkGallery projects={projects} reduced={pref.reduce||!loaded}/>
<SculptureReveal reduced={pref.reduce||!loaded}/>
<DeviceShowcase reduced={pref.reduce||!loaded}/>
<section id="services" className="section services"><div className="shell"><div className="eyebrow">What I build</div><div className="section-heading"><h2>Built around<br/>your business.</h2><p>A clear brief. Close collaboration. Something you can actually use.</p></div><div className="bee-service-flight" data-bee-anchor="services" aria-hidden="true"/><div className="service-list">{services.map(([name,desc,tags],i)=><article className="service-row" key={name}><span className="service-number">0{i+1}</span><div><h3>{name}</h3><div className="service-tags">{tags}</div></div><p>{desc}</p><a href={booking} target="_blank" rel="noopener noreferrer" aria-label={'Discuss '+name}><ArrowUpRight size={18}/></a></article>)}</div></div></section>
<section id="about" className="section about-section"><div className="shell"><div className="about-grid"><div className="about-photo about-real"><img src="/chris-real-photo-960.webp" srcSet="/chris-real-photo-480.webp 480w, /chris-real-photo-960.webp 960w, /chris-real-photo-1130.webp 1130w" sizes="(max-width:640px) min(360px, calc(100vw - 48px)), (max-width:1440px) 36vw, 564px" alt="Chris Conley, founder of The AI Fundi" loading="lazy" decoding="async" width={1130} height={1392}/></div><div className="about-copy"><div className="eyebrow">Meet your builder</div><h2>I’m Chris.<br/>The AI Fundi.</h2><p className="builder-role">Global AI Innovation Lead</p><p className="definition">“Fundi” means master builder in Swahili.</p><p>I bring 18+ years of global corporate experience across engineering, commercial strategy and AI innovation. Through The AI Fundi, I build websites, applications and practical AI systems around the way your business works.</p><p>You work directly with me, from the first conversation through to launch. I explain what we’re building, why it matters, and how your team can use it.</p><CTA>Meet me on a call</CTA></div></div><div className="process" id="how-it-works">{[['Understand your business','We start with listening. What needs to work better, who is it for, and what would a good result look like?'],['Build it together','You see the work as it develops. We test with real needs, gather feedback, and refine the details.'],['Hand over the keys','You get a working site or system, with clear guidance on how to run it and what comes next.']].map(([h,p],i)=><div key={h}><span className="step">0{i+1} / THE PROCESS</span><h3>{h}</h3><p>{p}</p></div>)}</div></div></section>
<section className="section testimonials"><div className="shell"><div className="eyebrow">In their words</div><h2>The people behind<br/>the projects.</h2><DiscoveryTestimonial/><div className="quotes">{[
['I’ve run my daycare for years without a website. Chris created my first one and helped me present my concept, routines, and values so clearly that parents now come to me already understanding how I work—and that makes choosing us much easier for them.','Business Owner','Hakuna Matata Daycare'],
['As a new nursing recruitment agency, I needed a professional online presence to start building trust with hospitals and candidates. Chris guided me from a blank page to a clear, credible website that explains our services, highlights our values, and gives international nurses an easy way to get in touch.','Co-Owner','Delta Personal Services'],
['Chris explained every step so clearly that my fears about launching a site disappeared. I love how he translated my ideas into a beautiful, on-brand website I can easily update myself, and I’m excited to keep building on it with a newsletter and more.','Owner','Blooms & Botanicals LLC']].map(([quote,role,name])=><figure key={name}><span className="quote-mark" aria-hidden="true">“</span><blockquote>{quote}</blockquote><figcaption><strong>{name}</strong>{role}</figcaption></figure>)}</div></div></section>
<section id="lab" className="section lab-section"><div className="shell"><div className="lab-grid"><div><div className="eyebrow">Want to learn to build?</div><h2>Come into<br/>The Fundi Lab.</h2><p>My community for AI-curious professionals who want to put the tools to work. Follow a build, ask questions, and learn by making something useful.</p><a href="https://www.skool.com/aifundi" className="button button-primary" target="_blank" rel="noopener noreferrer">Explore the Lab<ArrowUpRight/></a></div><div className="lab-list">{[[Layers,'Step-by-step builds','Templates and walkthroughs you can follow at your own pace.'],[Users,'Weekly live sessions','Bring your questions and work through them with support.'],[BookOpen,'Practical AI skills','Learn how to apply the tools to the work already on your desk.']].map(([Icon,h,p])=>{const I=Icon as typeof Layers;return <div key={h as string}><I/><div><h3>{h as string}</h3><p>{p as string}</p></div></div>})}</div></div><div className="audit" id="free-audit"><div><div className="eyebrow">Start with one small step</div><h3>The 15-Minute AI Audit.</h3><p>A free checklist to find where AI could save time in your business.</p></div><div>{audit==='success'?<p className="audit-status" role="status">You’re on the list. Check your inbox for the next step.</p>:<form onSubmit={subscribe}><label className="sr-only" htmlFor="audit-email">Email address</label><input id="audit-email" type="email" placeholder="you@yourbusiness.com" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/><button className="button button-primary" type="submit" disabled={audit==='sending'}>{audit==='sending'?'Sending…':'Send me the audit'}<ArrowUpRight size={17}/></button></form>}{audit==='error'&&<p className="audit-status" role="alert">That didn’t go through. Please try again or email hello@theaifundi.com.</p>}<small>The guide and occasional practical AI tips. Unsubscribe anytime. <a href="/privacy.html">Privacy policy</a></small></div></div></div></section>
<section className="section faq-section" id="faq"><div className="shell faq-grid"><div><div className="eyebrow">A few answers</div><h2>Before<br/>we begin.</h2></div><div>{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section>
<footer className="contact" id="contact"><div className="shell"><div className="contact-stage"><div className="contact-main"><div className="eyebrow">Start a project</div><h2>Have an idea?<br/><span>Let’s build it.</span></h2><p>A website that feels like you. An app worth opening.<br/>{' '}Let’s talk about what comes next.</p><div className="contact-actions"><CTA primary>Book a free 15 min call</CTA><a className="email" href="mailto:hello@theaifundi.com">hello@theaifundi.com</a></div></div><div className="contact-bee-anchor" data-bee-anchor="contact" aria-hidden="true"/></div><div className="footer-bottom"><div><a className="wordmark" href="#top">the ai fundi<span>+</span></a><div className="footer-meta">Chris Conley · Germany / Worldwide<br/>© {new Date().getFullYear()} The AI Fundi</div></div><div className="footer-links"><a href="https://www.skool.com/aifundi" target="_blank" rel="noopener noreferrer">The Lab</a><a href="/privacy.html">Privacy</a><a href="/terms.html">Terms</a><a href="#top">Back to top ↑</a></div></div></div></footer></main>
<Dialog><DialogTrigger asChild><button className="access-button" aria-label="Open accessibility and appearance settings"><Accessibility/></button></DialogTrigger><DialogContent className="access-panel"><DialogTitle>Make yourself comfortable.</DialogTitle><DialogDescription>Choose how this site looks and moves.</DialogDescription><div className="appearance-label">Appearance</div><div className="theme-options">{[['dark','Dark'],['light','Light'],['device','Use device']].map(([v,l])=><button key={v} aria-pressed={pref.theme===v} onClick={()=>update('theme',v)}>{l}</button>)}</div><div className="access-row"><label>Text size · {pref.size}%</label><div className="text-buttons"><button aria-label="Decrease text size" disabled={pref.size<=100} onClick={()=>update('size',Math.max(100,pref.size-10))}>A−</button><button aria-label="Increase text size" disabled={pref.size>=130} onClick={()=>update('size',Math.min(130,pref.size+10))}>A+</button></div></div>{[['contrast','High contrast'],['mono','Monochrome'],['underlines','Underline links'],['reduce','Reduce motion'],['readable','Readable font']].map(([key,label])=><div className="access-row" key={key}><label htmlFor={'setting-'+key}>{label}</label><Switch id={'setting-'+key} checked={!!pref[key as keyof Pref]} onCheckedChange={v=>update(key as keyof Pref,v)}/></div>)}<button className="reset-button" onClick={()=>setPref({...defaults,reduce:matchMedia('(prefers-reduced-motion:reduce)').matches})}>Reset all preferences</button></DialogContent></Dialog><span className="setting-status" role="status">{loaded?`${dark?'Dark':'Light'} appearance. Text size ${pref.size} percent. ${pref.reduce?'Reduced motion.':''}`:''}</span></>}
