"use client";
import {canvasFallback} from './canvas-fallback';
import {matchParticlePositions,smootherStep} from './morph-matching';
import {useEffect,useRef} from 'react';
import * as THREE from 'three';
// This first build uses raster samples. It is a motion proof, not a volumetric GLB likeness.
// See public/models/manifest.json and BUILD-STATUS.md for the production asset gate.
const N=57000;
const vertex=`attribute vec3 aTarget;attribute vec3 aHeadColor;attribute vec3 aBeeColor;attribute float aSeed;attribute float aLight;attribute float aBeeLight;attribute float aWing;uniform float uMorph;uniform float uTime;uniform float uSize;uniform float uMotion;varying float vAlpha;varying float vLight;varying vec3 vColor;void main(){
float m=uMorph;vec3 target=aTarget;float wingEase=smoothstep(.65,1.,m);float flap=sin(uTime*29.)*aWing*uMotion*wingEase;
target.y+=flap*.040;target.z+=flap*.065;
vec3 p=mix(position,target,m);float arc=sin(m*3.14159265);
p.x+=sin(aSeed*6.283)*arc*.045;p.y+=cos(aSeed*6.283)*arc*.035;p.z+=arc*.12;
p+=vec3(sin(uTime*.35+aSeed*6.),cos(uTime*.3+aSeed*7.),0.)*.0025*uMotion;
vec4 mv=modelViewMatrix*vec4(p,1.);gl_Position=projectionMatrix*mv;gl_PointSize=uSize*(9./-mv.z)*(.8+aSeed*.35);
vColor=mix(aHeadColor,aBeeColor,m);vLight=mix(aLight,aBeeLight,m);vAlpha=.35+vLight*.85;}`;
const fragment=`uniform vec3 uColor;uniform float uOpacity;uniform float uDark;varying float vAlpha;varying float vLight;varying vec3 vColor;void main(){float d=length(gl_PointCoord-.5);if(d>.5)discard;float a=smoothstep(.5,.15,d)*vAlpha*uOpacity;gl_FragColor=vec4(mix(vColor,uColor*(.55+vLight*.7),uDark),mix(smoothstep(.5,.12,d)*uOpacity,a,uDark));
#include <colorspace_fragment>
}`;
const flatVertex=`varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`;
const flatFragment=`uniform sampler2D uMap;uniform float uOpacity;uniform float uBranch;varying vec2 vUv;void main(){vec4 c=texture2D(uMap,vUv);float hi=max(max(c.r,c.g),c.b);float lo=min(min(c.r,c.g),c.b);float chroma=hi-lo;float lum=dot(c.rgb,vec3(.299,.587,.114));float alpha=max(smoothstep(.02,.085,chroma),1.-smoothstep(.17,.36,lum));if(uBranch>.5)alpha=max(alpha,smoothstep(.84,.94,lum));if(alpha<.05)discard;gl_FragColor=vec4(c.rgb,alpha*uOpacity);
#include <colorspace_fragment>
}`;
function rng(seed=90217){let n=seed;return()=>{n=(n*1664525+1013904223)>>>0;return n/4294967296}}
async function source(url:string){return new Promise<HTMLImageElement>((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=url})}
function sampleImage(img:HTMLImageElement,bee=false){const canvas=document.createElement('canvas');const s=700;canvas.width=canvas.height=s;const ctx=canvas.getContext('2d',{willReadFrequently:true})!;ctx.drawImage(img,0,0,s,s);const pixels=ctx.getImageData(0,0,s,s).data;const candidates:number[]=[];const weights:number[]=[];let sum=0;for(let y=5;y<s-5;y++)for(let x=5;x<s-5;x++){const i=(y*s+x)*4;const r=pixels[i]/255,g=pixels[i+1]/255,b=pixels[i+2]/255;const lum=.299*r+.587*g+.114*b;const chroma=Math.max(r,g,b)-Math.min(r,g,b);if(chroma<.045&&lum>.23)continue;const skin=!bee&&y<s*.62;const neighbor=(y*s+x+2)*4;const edge=Math.abs(pixels[i]-pixels[neighbor])+Math.abs(pixels[i+1]-pixels[neighbor+1]);const weight=(skin?1.7:1)*(1+Math.min(edge/40,1.3));sum+=weight;candidates.push(i);weights.push(sum)}
const rand=rng(bee?7521:8294);const pos=new Float32Array(N*3),color=new Float32Array(N*3),light=new Float32Array(N),wing=new Float32Array(N);for(let i=0;i<N;i++){const v=rand()*sum;let low=0,high=weights.length-1;while(low<high){const mid=(low+high)>>1;if(weights[mid]<v)low=mid+1;else high=mid}const p=candidates[low];const x=((p/4)%s)/s,y=Math.floor(p/4/s)/s;const lum=(pixels[p]*.299+pixels[p+1]*.587+pixels[p+2]*.114)/255;pos[i*3]=(x-.5)*3.55+(rand()-.5)*.004;pos[i*3+1]=(.5-y)*3.55+(rand()-.5)*.004;
// Deliberately shallow depth for the image-based preview; never represented as a complete 3D head.
const nx=(x-.49)/.34,ny=(y-.40)/.37;pos[i*3+2]=bee?.10*(1-Math.min(1,Math.abs(x-.55)*3)):.26*Math.sqrt(Math.max(0,1-nx*nx-ny*ny));color[i*3]=Math.pow(pixels[p]/255,2.2);color[i*3+1]=Math.pow(pixels[p+1]/255,2.2);color[i*3+2]=Math.pow(pixels[p+2]/255,2.2);light[i]=bee?(.18+lum*.85):(.1+lum*1.2)*(y>.69?.6:1);wing[i]=bee&&y<.53&&(x<.36||x>.72)?1:0;}return{pos,light,wing,color}}
function makeFlat(img:HTMLImageElement,branch=false){const texture=new THREE.Texture(img);texture.colorSpace=THREE.SRGBColorSpace;texture.needsUpdate=true;const material=new THREE.ShaderMaterial({uniforms:{uMap:{value:texture},uOpacity:{value:1},uBranch:{value:branch?1:0}},vertexShader:flatVertex,fragmentShader:flatFragment,transparent:true,depthWrite:false,side:THREE.DoubleSide});const plane=new THREE.Mesh(new THREE.PlaneGeometry(3.55*(img.width/img.height),3.55),material);return plane}
export default function Scene({dark,reduced}:{dark:boolean,reduced:boolean}){const mount=useRef<HTMLDivElement>(null);const state=useRef({dark,reduced});useEffect(()=>{state.current={dark,reduced};window.dispatchEvent(new Event('fundi-scene-change'))},[dark,reduced]);
useEffect(()=>{const host=mount.current;if(!host)return;let disposed=false,raf=0,last=0,time=0,scroll=window.scrollY,needsFrame=true;let pointerX=0,pointerY=0;const mobile=window.innerWidth<641;const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(35,window.innerWidth/window.innerHeight,.1,40);camera.position.z=9;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({alpha:true,antialias:false,powerPreference:'high-performance'})}catch{return canvasFallback(host,state)}renderer.setClearColor(0,0);renderer.setPixelRatio(Math.min(window.devicePixelRatio,mobile?1.5:2));renderer.setSize(window.innerWidth,window.innerHeight);host.appendChild(renderer.domElement);const group=new THREE.Group();scene.add(group);const materials:THREE.Material[]=[];const geometry:THREE.BufferGeometry[]=[];let cloud:THREE.Points|undefined,portrait:THREE.Mesh<THREE.PlaneGeometry,THREE.ShaderMaterial>|undefined,bee:THREE.Mesh<THREE.PlaneGeometry,THREE.ShaderMaterial>|undefined,branch:THREE.Mesh<THREE.PlaneGeometry,THREE.ShaderMaterial>|undefined;let shader:THREE.ShaderMaterial|undefined;let measures={hero:0,services:0,servicesHeight:0,contact:0,contactHeight:0,work:0,film:0,filmHeight:0,about:0};let worldH=2*Math.tan(THREE.MathUtils.degToRad(17.5))*9,worldW=worldH*camera.aspect;const normalized=(x:number,y:number)=>new THREE.Vector3((x-.5)*worldW,(.5-y)*worldH,0);const readBounds=()=>{const bound=(id:string)=>{const el=document.getElementById(id);if(!el)return{top:0,height:0};const b=el.getBoundingClientRect();return{top:b.top+window.scrollY,height:b.height}};const hero=document.querySelector('.hero-runway')!;const s=bound('services'),c=bound('contact'),f=bound('showcase');measures={hero:hero.getBoundingClientRect().height,work:bound('work').top,services:s.top,servicesHeight:s.height,contact:c.top,contactHeight:c.height,film:f.top,filmHeight:f.height,about:bound('about').top};needsFrame=true;start()};
scene.add(new THREE.AmbientLight(0xffffff,2));const key=new THREE.DirectionalLight(0xffffff,3);key.position.set(-3,4,6);scene.add(key);
Promise.all([source('/chris-conley-bust.webp'),source('/honeybee-reference.webp'),source('/footer-branch.webp')]).then(([a,b,c])=>{if(disposed)return;const h=sampleImage(a),original=sampleImage(b,true);const order=matchParticlePositions(h.pos,original.pos);const t={pos:new Float32Array(N*3),color:new Float32Array(N*3),light:new Float32Array(N),wing:new Float32Array(N)};for(let i=0;i<N;i++){const j=order[i];t.pos.set(original.pos.subarray(j*3,j*3+3),i*3);t.color.set(original.color.subarray(j*3,j*3+3),i*3);t.light[i]=original.light[j];t.wing[i]=original.wing[j]}const buffer=new THREE.BufferGeometry();const seed=new Float32Array(N),rand=rng();for(let i=0;i<N;i++)seed[i]=rand();buffer.setAttribute('position',new THREE.BufferAttribute(h.pos,3));buffer.setAttribute('aTarget',new THREE.BufferAttribute(t.pos,3));buffer.setAttribute('aHeadColor',new THREE.BufferAttribute(h.color,3));buffer.setAttribute('aBeeColor',new THREE.BufferAttribute(t.color,3));buffer.setAttribute('aLight',new THREE.BufferAttribute(h.light,1));buffer.setAttribute('aBeeLight',new THREE.BufferAttribute(t.light,1));buffer.setAttribute('aSeed',new THREE.BufferAttribute(seed,1));buffer.setAttribute('aWing',new THREE.BufferAttribute(t.wing,1));buffer.setDrawRange(0,mobile?28500:N);geometry.push(buffer);shader=new THREE.ShaderMaterial({uniforms:{uMorph:{value:0},uDark:{value:1},uTime:{value:0},uSize:{value:renderer.getPixelRatio()*(mobile?1.6:1.4)},uMotion:{value:1},uColor:{value:new THREE.Color('#8fc0f0')},uOpacity:{value:1}},vertexShader:vertex,fragmentShader:fragment,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending});materials.push(shader);cloud=new THREE.Points(buffer,shader);cloud.frustumCulled=false;group.add(cloud);portrait=makeFlat(a);bee=makeFlat(b);branch=makeFlat(c,true);group.add(portrait,bee);scene.add(branch);[portrait,bee,branch].forEach(p=>{materials.push(p.material);geometry.push(p.geometry)});host.dataset.ready='true';readBounds();}).catch(()=>{host.dataset.ready='false'});
function frame(now:number){raf=0;if(disposed)return;const dt=Math.min(.05,(now-last)/1000||.016);last=now;const {dark:isDark,reduced:reduce}=state.current;if(!reduce)time+=dt;const desired=window.scrollY;scroll=reduce?desired:scroll+(desired-scroll)*(1-Math.exp(-12*dt));const vh=window.innerHeight;let visible=true,morph=0,scale=1,opacity=1;let x=mobile?.5:.555,y=mobile?.39:.405;let rotation=0;const heroEnd=measures.hero-vh;const heroP=scroll/vh;let branchVisible=false;
if(reduce){visible=scroll<vh*.8;if(scroll+vh>measures.contact&&scroll<measures.contact+measures.contactHeight){visible=true;morph=1;x=mobile?.57:.81;y=mobile?.73:.43;scale=mobile?.4:.32;branchVisible=true}else{scale=mobile?.70:1}}
else if(scroll<heroEnd){morph=smootherStep((heroP-.20)/1.35);if(heroP<1.72){scale=mobile?.7:1;const dest=normalized(x,y);group.position.lerp(dest,.12)}else{const p=THREE.MathUtils.smoothstep(heroP,1.72,Math.max(2.1,heroEnd/vh));x=THREE.MathUtils.lerp(mobile?.5:.555,1.18,p);y=THREE.MathUtils.lerp(mobile?.37:.405,.78,p)+Math.sin(p*Math.PI)*.15;scale=THREE.MathUtils.lerp(mobile?.70:1,.25,p);rotation=-Math.sin(p*Math.PI)*.32;opacity=1-THREE.MathUtils.smoothstep(p,.86,1)}}
else if(scroll+vh>measures.services&&scroll<measures.about-vh*.35){morph=1;const p=THREE.MathUtils.clamp((scroll+vh-measures.services)/(measures.servicesHeight+vh*.65),0,1);x=THREE.MathUtils.lerp(-.15,1.12,p);y=.20+Math.sin(p*Math.PI*1.7)*.045;scale=mobile?.22:.24;rotation=Math.sin(p*4)*.13;opacity=Math.min(1,p*8,(1-p)*8)}
else if(scroll+vh>measures.contact&&scroll<measures.contact+measures.contactHeight){morph=1;const p=THREE.MathUtils.clamp((scroll+vh-measures.contact)/(vh*.8),0,1);x=THREE.MathUtils.lerp(1.15,mobile?.55:.81,THREE.MathUtils.smoothstep(p,0,1));const contactScreen=(measures.contact-scroll)/vh;y=contactScreen+(mobile?.80:.32)*Math.min(measures.contactHeight/vh,1.5);y+=Math.sin(time*2.2)*.007;scale=mobile?.32:.32;rotation=-.08;branchVisible=true}else visible=false;
if(group&&shader&&cloud&&portrait&&bee){group.visible=visible;shader.uniforms.uDark.value=isDark?1:0;shader.uniforms.uSize.value=renderer.getPixelRatio()*(mobile?1.6:1.4)*(isDark?1:1.25);const blending=isDark?THREE.AdditiveBlending:THREE.NormalBlending;if(shader.blending!==blending){shader.blending=blending;shader.needsUpdate=true}shader.uniforms.uMorph.value=morph;shader.uniforms.uTime.value=time;shader.uniforms.uMotion.value=reduce?0:1;const departure=THREE.MathUtils.smoothstep(morph,0,.12),arrival=THREE.MathUtils.smoothstep(morph,.87,1);const particleAlpha=isDark?1:Math.min(1,departure*1.35)*(1-arrival);shader.uniforms.uOpacity.value=Math.max(0,opacity)*particleAlpha;const p=normalized(x,y);group.position.copy(p);group.rotation.set(reduce?0:pointerY*.035,reduce?0:pointerX*.05,rotation);group.scale.setScalar(scale);cloud.visible=isDark||particleAlpha>.001;portrait.visible=!isDark&&morph<.12;bee.visible=!isDark&&morph>.87;portrait.material.uniforms.uOpacity.value=opacity*(1-departure);bee.material.uniforms.uOpacity.value=opacity*arrival;}
if(branch){branch.visible=branchVisible;const contactScreen=(measures.contact-scroll)/vh;const by=contactScreen+(mobile?.86:.51)*Math.min(measures.contactHeight/vh,1.5);branch.position.copy(normalized(mobile?.70:.87,by));branch.scale.setScalar(mobile?.42:.56);branch.material.uniforms.uOpacity.value=1}
const active=visible||branchVisible;if(active||needsFrame){renderer.render(scene,camera);needsFrame=false}if(!reduce&&active||Math.abs(desired-scroll)>.6)raf=requestAnimationFrame(frame)}
function start(){if(!raf&&!disposed){last=performance.now();raf=requestAnimationFrame(frame)}}const onScroll=()=>{needsFrame=true;start()};const pointer=(e:PointerEvent)=>{pointerX=e.clientX/window.innerWidth-.5;pointerY=e.clientY/window.innerHeight-.5;if(!state.current.reduced)start()};const resize=()=>{camera.aspect=window.innerWidth/window.innerHeight;camera.updateProjectionMatrix();worldH=2*Math.tan(THREE.MathUtils.degToRad(17.5))*9;worldW=worldH*camera.aspect;renderer.setSize(window.innerWidth,window.innerHeight);readBounds()};const change=()=>{needsFrame=true;readBounds()};const visibility=()=>{if(document.hidden){cancelAnimationFrame(raf);raf=0}else start()};const lose=(e:Event)=>{e.preventDefault();cancelAnimationFrame(raf);raf=0;host.dataset.ready='false'};const restore=()=>{host.dataset.ready='true';needsFrame=true;start()};window.addEventListener('scroll',onScroll,{passive:true});window.addEventListener('resize',resize);window.addEventListener('pointermove',pointer,{passive:true});window.addEventListener('fundi-scene-change',change);window.addEventListener('fundi-appearance',change);document.addEventListener('visibilitychange',visibility);renderer.domElement.addEventListener('webglcontextlost',lose);renderer.domElement.addEventListener('webglcontextrestored',restore);const observer=new ResizeObserver(readBounds);observer.observe(document.body);document.fonts.ready.then(()=>{if(!disposed)readBounds()});readBounds();return()=>{disposed=true;cancelAnimationFrame(raf);observer.disconnect();window.removeEventListener('scroll',onScroll);window.removeEventListener('resize',resize);window.removeEventListener('pointermove',pointer);window.removeEventListener('fundi-scene-change',change);window.removeEventListener('fundi-appearance',change);document.removeEventListener('visibilitychange',visibility);geometry.forEach(g=>g.dispose());materials.forEach(m=>{if(m instanceof THREE.ShaderMaterial&&m.uniforms.uMap)m.uniforms.uMap.value.dispose();m.dispose()});renderer.dispose();renderer.domElement.remove()}
},[]);return <div className="scene-canvas" ref={mount} aria-hidden="true"><img className="scene-fallback" src="/chris-conley-bust.webp" alt=""/></div>}
